name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?
      placeholder: I also thought about...

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Is this MVP (v0.1) or post-MVP?
      options:
        - MVP (v0.1) - Core functionality
        - Post-MVP - Nice to have
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of ISOTOPE does this relate to?
      options:
        - Core / Infrastructure
        - Worldgen / Structure Discovery
        - Loot Tables
        - UI / Visualization
        - Datapack Export
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
