package dev.isotope.registry;

import dev.isotope.Isotope;
import dev.isotope.data.LootSource;
import net.minecraft.resources.ResourceLocation;

import java.util.*;

/**
 * Registry of known Minecraft features that generate loot.
 *
 * Features are "fire-and-forget" decorations that aren't tracked like structures.
 * Unlike real structures, features have no bounding boxes, no persistent IDs,
 * and are not registered in Minecraft's structure registry.
 *
 * This registry provides known mappings from features to their loot tables,
 * allowing them to be displayed alongside structures in the UI.
 *
 * Examples:
 * - monster_room (dungeon) -> chests/simple_dungeon
 * - bonus_chest -> chests/spawn_bonus_chest
 * - desert_well -> archaeology/desert_well
 */
public final class FeatureRegistry {

    private static final FeatureRegistry INSTANCE = new FeatureRegistry();

    private final Map<ResourceLocation, FeatureDefinition> features = new LinkedHashMap<>();
    private boolean initialized = false;

    private FeatureRegistry() {}

    public static FeatureRegistry getInstance() {
        return INSTANCE;
    }

    /**
     * Initialize known vanilla features with loot.
     * Call this after structure scanning but before linking.
     */
    public void initialize() {
        if (initialized) return;
        features.clear();

        // === Vanilla Features with Loot ===

        // Spawner Dungeon (monster_room feature)
        // Generated by DungeonFeature, places a spawner room with 0-2 chests
        registerFeature("minecraft:monster_room",
            "Monster Room",
            "Spawner dungeon - a fire-and-forget feature, not a tracked structure",
            List.of("minecraft:chests/simple_dungeon"));

        // Bonus Chest (spawn_bonus_chest feature)
        // Only generated when "Bonus Chest" world option is enabled
        registerFeature("minecraft:bonus_chest",
            "Bonus Chest",
            "Starting chest when 'Bonus Chest' world option is enabled",
            List.of("minecraft:chests/spawn_bonus_chest"));

        // Desert Well (desert_well feature)
        // In 1.20+ contains suspicious sand with archaeology loot
        registerFeature("minecraft:desert_well",
            "Desert Well",
            "Desert well with suspicious sand (archaeology)",
            List.of("minecraft:archaeology/desert_well"));

        // Note: Other vanilla features don't have loot tables:
        // - Fossils: decorative bone blocks only
        // - Amethyst geodes: decorative, no loot
        // - Trees, ores, lakes, etc.: no loot tables

        initialized = true;
        Isotope.LOGGER.info("FeatureRegistry: initialized {} features with loot", features.size());
    }

    /**
     * Register a feature with its associated loot tables.
     */
    private void registerFeature(String featureId, String displayName, String description,
                                  List<String> lootTablePaths) {
        ResourceLocation id = ResourceLocation.parse(featureId);
        List<ResourceLocation> lootTables = lootTablePaths.stream()
            .map(ResourceLocation::parse)
            .toList();

        features.put(id, new FeatureDefinition(id, displayName, description, lootTables));
    }

    /**
     * Get all registered features.
     */
    public Collection<FeatureDefinition> getAll() {
        return Collections.unmodifiableCollection(features.values());
    }

    /**
     * Get feature by ID.
     */
    public Optional<FeatureDefinition> get(ResourceLocation id) {
        return Optional.ofNullable(features.get(id));
    }

    /**
     * Get features filtered by namespace.
     */
    public List<FeatureDefinition> getByNamespace(String namespace) {
        if ("*".equals(namespace)) {
            return new ArrayList<>(features.values());
        }
        return features.values().stream()
            .filter(f -> f.id().getNamespace().equals(namespace))
            .toList();
    }

    /**
     * Convert all features to LootSource objects.
     */
    public List<LootSource> getAllAsLootSources() {
        return features.values().stream()
            .map(FeatureDefinition::toLootSource)
            .toList();
    }

    /**
     * Check if a given ID is a known feature.
     */
    public boolean isFeature(ResourceLocation id) {
        return features.containsKey(id);
    }

    /**
     * Get all unique namespaces.
     */
    public Set<String> getNamespaces() {
        return features.values().stream()
            .map(f -> f.id().getNamespace())
            .collect(java.util.stream.Collectors.toCollection(LinkedHashSet::new));
    }

    /**
     * Total feature count.
     */
    public int size() {
        return features.size();
    }

    /**
     * Check if registry has been initialized.
     */
    public boolean isInitialized() {
        return initialized;
    }

    /**
     * Reset the registry.
     */
    public void reset() {
        features.clear();
        initialized = false;
    }

    /**
     * Feature definition with associated loot tables.
     */
    public record FeatureDefinition(
        ResourceLocation id,
        String displayName,
        String description,
        List<ResourceLocation> lootTables
    ) {
        /**
         * Convert to a LootSource for unified handling.
         */
        public LootSource toLootSource() {
            return LootSource.feature(id, displayName, description);
        }
    }
}
